#!/usr/bin/env sh
# Bootstrap a fresh .env with strong random credentials for Postgres + Redis.
# Idempotent: refuses to overwrite an existing .env (no surprise volume wipes).
#
# Usage:
#   ./scripts/setup.sh         # writes .env if missing, prints next steps
#   ./scripts/setup.sh --force # ignore existing .env (WARNING: see below)
#
# WARNING about --force:
#   Changing POSTGRES_PASSWORD after Postgres has already initialized its data
#   directory does NOT update the stored password. You'd also need
#   `docker compose down -v` (which deletes monitor history). Avoid --force
#   unless you're rotating creds before any real data exists.

set -e

FORCE=0
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//' | head -20
      exit 0
      ;;
  esac
done

if [ -f .env ] && [ "$FORCE" -ne 1 ]; then
  echo ".env already exists — leaving it alone."
  echo "Run with --force to regenerate (warning: requires docker compose down -v if Postgres has data)."
  exit 0
fi

# Strong random secrets (32 bytes hex = 64 chars). Prefer openssl; fall back to /dev/urandom.
gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

POSTGRES_PASSWORD=$(gen_secret)
REDIS_PASSWORD=$(gen_secret)
OBJECT_ACCESS_KEY=$(gen_secret | cut -c1-20)
OBJECT_SECRET_KEY=$(gen_secret)

cat > .env <<EOF
# oo-workers — generated by scripts/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Keep this file out of version control. Rotating these values after first boot
# requires \`docker compose down -v\` (Postgres password is baked into the data dir).

# --- Postgres ---
POSTGRES_USER=oo
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=oo_workers
POSTGRES_PORT=5432

# --- Redis ---
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_PORT=6379

# --- UI / HTTP ---
UI_PORT=3001
# OO_BIND_ADDR=0.0.0.0   # uncomment to expose UI beyond localhost (pair with TLS)

# --- Worker tuning ---
LOG_LEVEL=info
API_CHECK_CONCURRENCY=10
URL_MONITOR_CONCURRENCY=20
QA_PROJECT_CONCURRENCY=5

# --- Object storage (bundled RustFS by default) ---
# Override OO_OBJECT_STORAGE_ENDPOINT to point at AWS S3, R2, B2, etc.
# When you do, the bundled rustfs container becomes unused (operator can
# remove it from compose or just leave it idle).
OO_OBJECT_STORAGE_ENDPOINT=http://rustfs:9000
OO_OBJECT_STORAGE_REGION=us-east-1
OO_OBJECT_STORAGE_BUCKET=oo-workers
OO_OBJECT_STORAGE_ACCESS_KEY=${OBJECT_ACCESS_KEY}
OO_OBJECT_STORAGE_SECRET_KEY=${OBJECT_SECRET_KEY}

# --- Multi-region master URL (only the TLS overlay needs this) ---
# OO_DOMAIN=monitor.example.com
EOF

chmod 600 .env

echo "✅ wrote .env with random Postgres + Redis + RustFS credentials"
echo ""
echo "next:"
echo "  docker compose up -d                # boot the stack"
echo "  docker compose exec worker bun scripts/create-api-key.ts --name first"
echo "                                       # → paste the printed oo_… key into the login screen"
echo ""
echo "for HTTPS via the Caddy overlay:"
echo "  OO_DOMAIN=monitor.example.com docker compose \\"
echo "    -f docker-compose.yml -f docker-compose.tls.yml up -d"
